version: '3'

networks:
    rabbit_net:
        external: true

services:
    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        ports:
        - 5672:5672
        - 15672:15672
        networks:
        - rabbit_net

